package App::Mist::Command::compile;
# ABSTRACT: Recompile mpan-install for this project

use 5.010;

use App::Mist -command;

use App::Mist::Utils qw/ append_module_source append_text_file /;
use Module::Path qw/ module_path /;

use Try::Tiny;
use File::Copy;
use File::Share qw/ dist_file /;
use Path::Class qw/ dir /;
use Cwd;

use ExtUtils::Manifest;

sub execute {
  my ( $self, $opt, $args ) = @_;

  my $ctx  = $self->app->ctx;
  my $home = $ctx->project_root;
  my $mpan = $ctx->mpan_dist;

  chdir $home->stringify;


  print "Checking sanity of project files\n";
  if ( -r -f $home->file('MANIFEST.SKIP')->stringify ) {
    my $skipchk = ExtUtils::Manifest::maniskip();

    # .claude/ holds Claude Code session state, including full-repo worktrees.
    # Unexcluded it bloats a regenerated MANIFEST and gets walked by the shebang
    # scan below. Flag it like a bad shebang so the build-master adds the rule.
    if ( -d $home->subdir('.claude')->stringify
         and not $skipchk->( '.claude/x' ) ) {
      print STDERR
        "WARNING: .claude/ is present but not excluded by MANIFEST.SKIP\n",
        "         add '^\\.claude/' so its session/worktree state is not packaged\n";
    }

    my ( @invalid_shebang, @tainted_shebang );
    $home->traverse(sub {
      my ($child, $cont) = @_;
      my $local = $child->relative( $home );
      return if $skipchk->( $local );
      if ( $child->is_dir ) {
        return if $child->basename eq 'perl5'; # don't descent into mist env
        return if $child->basename eq 'node_modules'; # don't descent into npm lib
        return $cont->();
      } else {
        my $fh = eval{ $child->openr }
          or return;
        my $shebang = <$fh>;
        return unless defined $shebang;
        push @invalid_shebang, $local if $shebang =~ m{^#.*bin/perl};
        push @tainted_shebang, $local if _shebang_enables_taint( $shebang );
      }
    });

    print STDERR "WARNING: invalid shebang found (use '#!/usr/bin/env perl' instead):",
      join( qq{\n  }, '', @invalid_shebang ), "\n" if @invalid_shebang;

    # Reported separately from the shebang-style warning, and after it, because
    # the two remedies conflict: the fix suggested above cannot be applied to a
    # tainted script.
    print STDERR
      "WARNING: taint mode (-T) in a shebang cannot work in a mist project:",
      join( qq{\n  }, '', @tainted_shebang ), "\n",
      "         Taint makes perl ignore PERL5LIB, which is how mist hands a\n",
      "         script the project's libraries - so these see none of ./perl5\n",
      "         and every vendored module is missing. '#!/usr/bin/env perl -T'\n",
      "         does not even start (env looks for a program named 'perl -T').\n",
      "         If a script must run tainted, give it the paths with explicit\n",
      "         -I switches; the environment cannot carry them.\n"
      if @tainted_shebang;
  } else {
    print STDERR "WARNING: no MANIFEST.SKIP file found in project root\n";
    print STDERR "         skipping sanity scan of project files\n";
  }

  try {

    my $assert  = "\n# TODO: assertions not yet implemented\n";

    my @prepend = $ctx->dist->get_prepended_modules;
    my @notest  = $ctx->dist->get_modules_not_to_test;
    my @prereqs = $ctx->fetch_prereqs;

    my $perl_version = $ctx->perl_version;

    print "Generating mpan-install\n";

    open my $out, ">", "mpan-install.tmp" or die $!;
    print $out "#!/usr/bin/env perl\n";
    print $out "# Generated by App::Mist version $App::Mist::VERSION\n\n";

    append_module_source( 'Getopt::Long' => $out, begin_lift => 1 );

    append_module_source(
      'App::cpanminus::fatscript' => $out,
      until => qr/# END OF FATPACK CODE\s*$/,
    );

    append_module_source( 'Getopt::Long::Parser' => $out, begin_lift => 1 );
    append_module_source( 'Devel::CheckBin'      => $out, begin_lift => 1 );
    append_module_source( 'Devel::CheckLib'      => $out, begin_lift => 1 );
    append_module_source( 'Devel::CheckCompiler' => $out, begin_lift => 1 );
    append_module_source( 'Probe::Perl'          => $out, begin_lift => 1 );

    append_module_source( 'Mist::Distribution' => $out );
    append_module_source( 'Mist::Environment'  => $out );

    # The generation ladder is shared code, not installer-private: mist commands
    # that move the live environment forward call the same module directly, so the
    # host and the build-master cannot drift apart on how a generation is named,
    # seeded, promoted or activated.
    append_module_source( 'Mist::Generation'   => $out );

    print $out $ctx->mist_environment->as_code( package => 'DISTRIBUTION' );

    append_text_file(
      dist_file( 'App-Mist', 'cmd-wrapper.bash' ) => $out,
      package => 'CMD_WRAPPER::Bash',
    );

    # has to be included before Mist::Script::install so it has unfettered
    # access to @ARGV
    append_module_source('Mist::Script::perlbrew' => $out, VARS => [
      PERLBREW_ROOT            => $ctx->perlbrew_root,
      PERLBREW_DEFAULT_VERSION => $perl_version,
    ]);

    append_module_source( 'Mist::Script::install' => $out, VARS => [
      MPAN_DIST_DIR      => $mpan->relative( $home ),
      PREREQUISITE_DISTS => \@prereqs,
    ]);

    append_module_source( 'Mist::Script::usage' => $out, verbatim => 1 );

    print $out <<"VERSION_INFO";

=head1 VERSION

 This script was generated by App::Mist version $App::Mist::VERSION

=cut

VERSION_INFO

    close $out;

    unlink "mpan-install";
    rename "mpan-install.tmp", "mpan-install";
    chmod 0755, "mpan-install";

  } catch {

    warn "$_\n";

  } finally {

    unlink "mpan-install.tmp"

  };

}

# Does this shebang put perl into taint mode? Pure, so the parsing is testable
# on its own - and it needs parsing rather than a match, because a bare /-T/
# catches an interpreter *path* like /opt/perl-T/bin/perl, and a non-perl
# interpreter may take a -T of its own that means something else entirely.
sub _shebang_enables_taint {
  my ( $shebang ) = @_;
  return 0 unless defined $shebang and $shebang =~ m{^#!\s*(\S+)(.*)$};

  my ( $interpreter, $rest ) = ( $1, $2 );
  my @args = split ' ', $rest;

  if ( $interpreter =~ m{(?:\A|/)env\z} ) {
    # `#!/usr/bin/env perl -T`: the interpreter is env and perl is its argument.
    # Worth flagging even though the kernel hands env "perl -T" as a single
    # word, so it never starts - that failure is opaque enough to be worth a
    # warning of its own.
    return 0 unless @args and $args[0] =~ m{\Aperl[\d.]*\z};
    shift @args;
  } else {
    return 0 unless $interpreter =~ m{(?:\A|/)perl[\d.]*\z};
  }

  # -T alone, or bundled: -wT and -Tw both taint, -w does not. A long option
  # never does.
  return ( grep { /\A-[^-]*T/ } @args ) ? 1 : 0;
}

1;

__END__

=pod

=head1 NAME

App::Mist::Command::compile - regenerate mpan-install from mistfile and cpanfile

=head1 SYNOPSIS

  mist compile

=head1 DESCRIPTION

Reads the project's F<mistfile> and F<cpanfile> and regenerates
F<./mpan-install> -- the fatpacked, self-contained installer that bootstraps
F<./perl5/> on any host. Run C<compile> after every change to either file.

Before generating, C<compile> sanity-checks the project: when a
F<MANIFEST.SKIP> is present it scans the non-skipped files for hard-coded
C<#!.../bin/perl> shebang lines and warns about them (portable scripts
should use C<#!/usr/bin/env perl>). It also warns when a F<.claude/>
directory is present but not excluded by F<MANIFEST.SKIP> -- left unexcluded
its session state and full-repo worktrees bloat a regenerated F<MANIFEST>;
add C<^\.claude/> to silence it.

Together with the generated F<./mpan-install>, C<compile> is one of the two
commands you run routinely. See also L<mist init|App::Mist::Command::init>,
which chains C<compile>, dependency injection and C<mpan-install> into a
single step.

=head1 SEE ALSO

L<App::Mist::Command::init>

=head1 AUTHORS

Sebastian Willert <s.willert@wecare.de>

=cut
