=head1 App::Mist

=over 4

=item

Let mist itself use mistfile and cpanfile (e.g. testing and version info)

=back

=head1 MERGING

=over 4

=item

When merging another mist-managed dist, also merge the content
of their mistfile. E.g. as (in local mistfile):

  for 'Other::Dist' => {
    notest 'Term::ReadKey';
  }

=back

=head1 BUGS

=over 4

=item

Figure out why Devel::CheckCompiler and friends don't work
on our servers (File::Temp seems to return files in read-only
directories or even read-only files and is the likely issue
here)

=head1 PERL5 LIB HANDLING

=over 4

=item

Figure out how to handle differences in compiled perl API,
e.g. a perl compiled with -Dusethreads

=back
